### PR TITLE
Add boolean hyperthreading for structure cpu.

### PR DESCRIPTION
**Pull request by rhumroux**
Hi,

 I'm a new quattor user from T2_BE_IIHE, this is my first pull request, so I apologize beforehand if I'm doing something wrong !

I'd like to make changes to how slots are calculated for hyperthreaded CPUs. 
This merge request just adds a new field to the cpu structure. It will allow us to compute the number of logical cores for CPUs with hyperthreading. It defaults to false.

Cheers
Romain

### CODE REVIEW

**Comment by samary** [comment]
Test this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@samary i don't know why you can't trigger the tests
@rhumroux to be able to trigger the tests, you need to join https://github.com/orgs/quattor/teams/developers

**Comment by jrha** [comment]
@samary IIRC Jenkins is case sensitive.

**Comment by jrha** [comment]
@rhumroux I am happy to add you to the developers team if someone will vouch for you. :smile:

**Comment by jrha** [comment]
LGTM

**Comment by rhumroux** [comment]
thanks @jrha ! @samary is on holidays :) It can wait until he comes back. Or until the next quattor workshop we host in Brussels ;)

**Comment by stdweird** [comment]
@jrha i've met @rhumroux, he's real :smile:

**Comment by jrha** [comment]
Good enough for me

**Comment by jrha** [comment]
As noted in quattor/template-library-grid#153: hyperthreading is Intel specific (and a trademark) other vendors implement similar technologies, perhaps this should should have been SMT (simultaneous multithreading)?

**Comment by stdweird** [comment]
@jrha than it should be a long, not a boolean (power8 allows you to change it, even at runtime)

**Pull request merged**
