### PR TITLE
Remove component code parameter

### PR DESCRIPTION
**Pull request by jrha**
Based on and finishes #74

### CODE REVIEW

**Comment by ned21** [comment]
First commit needs to be removed since it is made redundant by the second. If this functionality was removed some time back then I think it should be OK just to yank the structure without a deprecation warning first. People may need to do some code clean up as part of their upgrade, but that's OK - they will get a hard error, and there's an easy local workaround if they really can't delete that code.

**Comment by jrha** [comment]
I discussed this with @stdweird and we settled on the two stage approach, as it is possible that sites are still writing to the parameter (useless but harmless), so just yanking it seems mean.

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha the tests... they are... :green_apple: :green_book: :green_heart: :tea: green
might want to turn this in a protected repo

**Comment by jrha** [comment]
!!!!!
:astonished:

Done.

**Comment by jrha** [comment]
Are we expecting anything else from the tests than this?
> pan annotations ok
>
> [OK] expected panc failure due to missing data.

**Comment by stdweird** [comment]
@jrha euhm, i can't merge things, but LGTM
@ned21 can you press shiny green button?

**Pull request merged**
