### PR TITLE
quattor/functions/network copy_network_params: bootproto=none for unconfigured interfaces

### PR DESCRIPTION
**Pull request by jouvin**
- Required for `nmstate` to work properly for unconfigured interfaces

I mark this PR as backward incompatible as it changes the resulting profile compared to previous version but I think it fixes something that was wrong but working with initscripts (because they don't care about interfaces not enabled on boot).

### CODE REVIEW

**Comment by jouvin** [comment]
The `panlint` error is due to a variable called `MTU`, a too short name. I'd prefer to keep it to avoid breaking backward compatibility but if you prefer to do it, it should not be too much an issue for GRIF... If we keep it, is there a magic line to avoid checking this name and raising an error?

**Comment by jrha** [comment]
I'd prefer if it were called something less ambiguous like `INTERFACE_MTU`, I've checked and we don't use it at RAL.

**Comment by jrha** [comment]
I don't think I've shared it before, but we use this simple script for situations where we need to rename something globally: https://gist.github.com/jrha/f8373418cac4ed2ad6f5e5be08d096c3

**Comment by jouvin** [comment]
Ok, I'll do it.

**Comment by jrha** [comment]
Thanks!

**Comment by jrha** [comment]
Can you remove the `(Ã)` from the commit message?

**Comment by jouvin** [comment]
Sure!

**Comment by jouvin** [comment]
Should be ok now...

**Pull request merged**
