### PR TITLE
Test basic pan linting tests

### PR DESCRIPTION
**Pull request by jrha**
Run panlint against files changed in each PR.

Refactors pan/functions in order to test and then satisfy the linter.

### CODE REVIEW

**Comment by jrha** [comment]
@stdweird can you see the travis test results?

**Comment by stdweird** [comment]
yes, both the travis and the jenkins one.

**Comment by stdweird** [comment]
i hope you do not expect the current version to be merged?
once there's a repo for the lint code, i can deploy this also on jenkins

**Comment by jrha** [comment]
Doesn't jenkins have enough to do already?
I have also been looking at https://github.com/markstory/lint-review.

**Comment by stdweird** [comment]
it could be intergrated in maven tools and run e.g. on the each PR of the components (together with a test of annotations).

**Comment by jrha** [comment]
I really see it as a code-review step rather than an actual test, unit tests should fail on functionality not coding style.

**Comment by stdweird** [comment]
@jrha but your lint regexps allow for quite some false positives (i'd comment on them if it was a PR :smile: )
also, i have a script that can cleanup all `include {}` and nlist/dict issues, should run that first

**Comment by jrha** [comment]
There's a reason it's not a PR.

**Comment by jrha** [comment]
Updated to use latest version of panlint from pan repo (merged in quattor/pan#104).

**Comment by stdweird** [comment]
@jrha do you want to add a milestone?

**Comment by jrha** [comment]
Is the approach of fetching the latest panlint from Github good enough for now?

**Comment by stdweird** [comment]
sure

**Comment by stdweird** [comment]
@jrha thanks!

**Pull request merged**
