### PR TITLE
 test_templates: add config values for metaconfig templates 

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha only 30 or so left to add 😄

**Comment by jrha** [comment]
This is definitely an improvement, but if I understand this correctly:
1. Only one version will get tested.
2. This will need updating in-sync with changes to `configuration-modules-core` when things change.

**Comment by stdweird** [comment]
@jrha yes, this is definetly not the final solution. probably some discussion during a workshop is needed. the test template (esp for metaconfig) should be maintained in metaconfig as part of a unittest, an djust included here. anyway, that will be for another time...

**Comment by jrha** [comment]
@stdweird I've applied the removal of the reference to the missing version template, could you rebase and squash?

**Comment by stdweird** [comment]
@jrha requires https://github.com/quattor/configuration-modules-grid/pull/133 and templates pushed to master

**Comment by jrha** [comment]
Templates were pulled in during RC1, see https://github.com/quattor/template-library-core/commit/3e42dc500df552ed65893d69983d3f00d09162fa#diff-fa823a08480edde64b6d53b442a783da.

**Pull request merged**
