### PR TITLE
introduce boolean to ignore filesystem and/or partition in (ks) AII

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by ned21** [comment]
What's the purpose of this field? When would someone find it useful?

**Comment by stdweird** [comment]
we are trying to use ncm-filesystems on multipath devices that are way too complicated to get working during anaconda (IB SRP targets using named `/dev/mapper/abc` devices).

**Comment by ned21** [comment]
Make sense - can you add that rationale to the commit log please? Or perhaps the annotation? Am feeling inspired/motivated by this [tweet](https://twitter.com/mjg59/status/852633050550648832) today :)

**Comment by stdweird** [comment]
@ned21 commit message updated

**Pull request merged**
