### PR TITLE
Add script as primitive template test

### PR DESCRIPTION
**Pull request by stdweird**
To replace the hardcoded test in jenkins

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha tagged 15.8, if merged, together with https://github.com/quattor/configuration-modules-grid/pull/82 and https://github.com/quattor/configuration-modules-core/issues/588 allows us to run a primitive test of the core templates

https://github.com/quattor/release/issues/109

**Comment by stdweird** [comment]
@jrha needless to say, the script should not be part of the release of the core templates.

**Comment by jrha** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha to pass we need
* new template from the components
* this PR merged so we can used it jenkins

**Comment by jrha** [comment]
:sob:

**Comment by jrha** [comment]
I was being overly optimistic.

**Pull request merged**
