### PR TITLE
Add basic support for GPUs

### PR DESCRIPTION
**Pull request by drossy**
Adds a very basic hardware support for GPUs

### CODE REVIEW

**Comment by drossy** [comment]
Please test this

**Comment by drossy** [comment]
please test this

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@drossy tests fail for unrelated reason (so don't try to fix them 😄 )

**Comment by stdweird** [comment]
@drossy however, it would be nice if you could sqaush the commits, we don't really like "fix typo" commits

**Comment by jrha** [comment]
@hpcugentbot please test this

**Pull request merged**
